### ISSUE TITLE
Create CRUD for users

### ISSUE THREAD

**Issue by miroslavzeman** [MikePi21/story-game-exercise#5]
### Description

Create a **controller** with basic CRUD operations. You should be able to call endpoints from the swagger UI, so don't forget to add valid **attributes** to class or methods.

## Controller

Your controller endpoints should look like.

- `/users` - GET should return list of all users 
- `/users/:id` - GET should return a specific user with given ID or throw an exception and return **404 status code** in response
- `/users/:id` - DELETE should return void and remove specific user with given ID
- `/users` - POST - should create new user 
- `/users/:id` - PUT/PATCH - study the difference between them and choose one. Should update user info based on given ID

## Service

Your service should have an `IUserService` interface with all CRUD operations. You should **inject** the service into the controller, and call the valid service method on each controller's endpoint, ex. on `/users` request you should trigger a method like `userService.getAll()` through the controller, and the service should handle the logic of getting all the necessary data from data context.

## Diagram overview

```mermaid
classDiagram

    class UsersController{
      <<controller>>
      +User[] all()
      +User find(string userId)
      +User create(UserCreateCommand command)
      +User update(UserUpdateCommand command)
      +void remove(string userId)
    }

    class IUsersService{
       <<interface>>
      +User[] all()
      +User find(string bookId)
      +User create(UserCreateCommand command)
      +User update(UserUpdateCommand command)
      +void remove(string userId)
    }

    class UsersService{
       <<service>>
    }



   UsersController --> UsersService : Controller calls service through interface
   IUsersService --> UsersService : Service implements all methods from interface
           
```

## Expected result

- [ ] - you are able to call all the endpoints from swagger UI
- [ ] - there is a controller for handling books requests, ex. UsersController
- [ ] - there is a service for handling users logic, ex. UsersService which implements IUsersService interface with all the CRUD methods
- [ ] - all the CRUD operations work with database.

**Comment by MikePi21** [comment]
done
